fix crash if a folder's parent is newer than itself
Folders are returned in creation order, not nesting order.
So when iterating through the folder list, we can't assume that the parent folder's __fullname has been set yet.

Fixes:

    Traceback (most recent call last):
      File "/net/skaia/projects/refern-takeout/refern_takeout.py", line 232, in <module>
        main()
      File "/net/skaia/projects/refern-takeout/refern_takeout.py", line 40, in main
        compute_fullnames(folders, items)
      File "/net/skaia/projects/refern-takeout/refern_takeout.py", line 68, in compute_fullnames
        fullname = folders[folder["parentFolderId"]]["__fullname"] + "/" + fullname
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
    KeyError: '__fullname'